stages :
  - install
  - test
  - deploy

variables:
  HEROKU_AUTH_TOKEN: ${HEROKU_AUTH_TOKEN}
  HEROKU_APP_NAME: tp2-serverless-aseds

dependencies:
  stage: install
  image: node:12-alpine
  script:
    - npm install

test:
  stage: test
  image: trion/ng-cli-karma
  allow_failure: true
  script:
    - npm install
    - ng test --progress false --watch false


deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_AUTH_TOKEN
